### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [arithy/packcc#3]
I suggest to reuse a higher level build system than [your current make scripts](https://github.com/arithy/packcc/commit/27c06965bacb8bb6ef6d59875a7232528a825096 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by arithy** [comment]
Thank you for your proposal.
Currently, I don't plan to use them since the source code of packcc is already portable enough.
I might begin to consider using the tools when a user of a platform other than Linux, BSD, macOS, and Windows appears.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.16/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by arithy** [comment]
I want basically users to prepare their own build environment, because:
- PackCC is a highly portable single-source program, which can be built just using a C compiler command once,
  ~~~
  cc -o packcc packcc.c
  ~~~
- PackCC mostly uses standard C library functions, considering portability, and prepares alternative implementations for nonportable functions like `strnlen()`.

Again, I have no plan to use CMake or Autotools for now because I don't feel their necessity as for PackCC.

**Comment by andrewchambers** [comment]
Autotools is often worse than useless, not only is it a required dependency, but can dramatically slow down the build because the configure scripts are comically slow.

**Comment by arithy** [comment]
@elfring,
I'm going to close this issue because it seems that most people don't feel this issue is _an issue_.
If you have any objection against closing this issue, let me know by the end of this month (Aug. 2022).

**Comment by elfring** [comment]
:thought_balloon: I hope that interests can grow also for applications of build system generators.

**Comment by arithy** [comment]
It might be just your impression, and isn't persuasive.

**Comment by masatake** [comment]
@arithy How about adding a FAQ entry to README.md?

e.g.
```
diff --git a/README.md b/README.md
index 7510d17..e4a4e9e 100644
--- a/README.md
+++ b/README.md
@@ -705,3 +705,15 @@ int main() {
 You can find the more practical example in the directory [`examples/ast-tinyc`](examples/ast-tinyc).
 It builds an AST (abstract syntax tree) from an input source file
 written in [Tiny-C](http://www.iro.umontreal.ca/~felipe/IFT2030-Automne2002/Complements/tinyc.c) and dump the AST.
+
+## FAQ ##
+
+<dl>
+	<dt>Will you support another build system than other Make?</dt>
+	<dd>No. I have no plan to use CMake or Autotools for now because I don't feel their necessity as for PackCC.</dd>
+	<dt>Which language is assumed for building packcc command?</dt>
+	<dd>C language. C++ is not assumed for building packcc command.</dd>
+	<dt>Which language is assumed for compiling the source code generated by packcc?</dt>
+	<dd>C language. C++ language is not assumed for compiling the source code generated by packcc.
+		However, you can link the object code compiled from the source code to your C++ code.</dd>
+</dl>
```

**Comment by arithy** [comment]
@masatake, it's a good idea. Thank you for the suggestion. I'll add the FAQs.

**Comment by elfring** [comment]
>I have no plan to use CMake or Autotools for now because I don't feel their necessity as for PackCC.

:crystal_ball: Under which circumstances will software users feel the need for increasing applications of known functionality?

**Comment by arithy** [comment]
I stated https://github.com/arithy/packcc/issues/3#issuecomment-565802937 as the reason why I don't feel their necessity.
The discussion will become an infinite loop. I have decided to close this issue.
