### ISSUE TITLE
Need additional conditions to not shift by 32 on additional 32 bit platforms

### ISSUE THREAD

**Issue by derekschrock** [arithy/packcc#34]
From this ifndef only Windows 32bit will not include the `x |= x >> 32` code.

https://github.com/arithy/packcc/blob/master/src/packcc.c#L913

Other 32 bit platforms will include this code.  On FreeBSD 32 bit clang 10, and 11 (and it appears all other) result in a crashing program.

For example after building packcc, universal-ctags attempts to run packcc with sample tag file.  Output from FreeBSD ports on a 32 bit system building universal-ctags port using arinty/packcc:

http://beefy15.nyi.freebsd.org/data/130releng-i386-default/46fc7df8540c/logs/universal-ctags-p5.9.20210411.0.log

In this case populate_bits() returns -1 with optimized compiling.

I believe this is [undefined behavior](https://port70.net/~nsz/c/c11/n1570.html#6.5.7p3) for `x >> 32` on 32 bit systems where x is 4 bytes resulting in a compiler warning:

```
./misc/packcc/src/packcc.c:914:12: warning: shift count >= width of type [-Wshift-count-overflow]
x |= x >> 32; 
           ^  ~~  
1 warning generated.
```

assuming x is > 0

Optimized gcc appears to do the right thing resulting in 0 however unoptimized gcc will result in x's original value.

Optimized clang will result in max value of the given type or -1 on 32bit and unoptimized clang like gcc will result in the original value.

I'm not totally sure if this is a FreeBSD only problem.  It's possible you can get lucky with gcc compiling optimized or unoptimized and it will run without issue?

I don't know if there's a single ifndef or macro that could be used to handle all platforms?  Would it make sense to check the sizeof x during runtime and put the `x |= x >> 32` in an if block?

For the short term for FreeBSD at I can patch it out on 32bit systems.

**Comment by arithy** [comment]
OK, I'll fix it.
Before that, can you let me know the result of the following command in your environment?
```
echo | clang -std=gnu89 -dM -E - | grep __SIZEOF_SIZE_T__
```
I expect the below.
```
#define __SIZEOF_SIZE_T__ 4
```
If it is so, I'll fix the macro condition using `__SIZEOF_SIZE_T__`.

**Comment by derekschrock** [comment]
Yep. 

FreeBSD 64 bit
`#define __SIZEOF_SIZE_T__ 8`

FreeBSD 32 bit
`#define __SIZEOF_SIZE_T__ 4`

**Comment by arithy** [comment]
I've pushed the modification. Please confirm it.
