### ISSUE TITLE
Lexical state support

### ISSUE THREAD

**Issue by ccleve** [arithy/packcc#49]
JFlex has nice support for controlling lexical state. I assume that Flex does as well. In JFlex you call yybegin(int state) to start a new state, and then any rules that are wrapped by the state will get invoked:

%%
<MYSTATE> {
  {myrule}  { only gets recognized if state==MYSTATE }
} 

Go here and search for "lexical state": https://jflex.de/manual.html

This is really useful. Does PEG or Packcc have a similar concept?

**Comment by arithy** [comment]
@ccleve, I'll close this issue since your request is technically incompatible with PEG parsers.

**Comment by arithy** [comment]
Hello @ccleve, I have introduced 'programmable predicates' and it should be fulfill your needs. It can be realized by restricting to access only 'marker variables', which are guaranteed not to cause parsing context corruption. If you still have interests, please try it.

**Comment by ccleve** [comment]
Thank you. I'll have a look.
