### ISSUE TITLE
Questions not answered in the README

### ISSUE THREAD

**Issue by apaz-cli** [arithy/packcc#51]
# Questions

These are things that I've been wondering. Other people probably have the same questions, so they should probably be covered in the README.

1. What is the storage duration of `$$`? There's actually a StackOverflow question about this. https://stackoverflow.com/questions/66145396/how-to-use-the-value-returned-by-a-packcc-parser

2. How can I read from a file instead of stdin?

3. Suppose I want to generate an AST. Am I supposed to generate it with $$ inside the rules manually? Is there some way to make this easier? Or is generating an AST beyond the scope of this parser generator?

4. Can I define an action and an error action on the same rule?

5. What's the deal with whitespace? It seems to be ignored. What if my language were whitespace-sensitive? Does it suck the whitespace out of string literals?

6. My language has C style single and multi-line comments in it. How can I ignore those like whitespace seems to be ignored?

Thanks, and you've got a very impressive project.

**Comment by ccleve** [comment]
Yes, examples would be really helpful. 

I'm currently struggling with the right syntax to create an iterator that supplies input over an array of ints (unicode codepoints) or bytes (UTF-8). This is a C-code thing, not a PEG thing, but it would speed development quite a bit. I'm thinking I have to create a ParseState structure with the input data and a pointer to the right getCharacter() function, and then pass it in as auxil. Haven't got it straight yet.

Example AST-generation code would be great.

You might find some use-cases for a parser here: https://github.com/antlr/grammars-v4 Pick some interesting ones and re-implement them in packcc.

**Comment by arithy** [comment]
> You might find some use-cases for a parser here: https://github.com/antlr/grammars-v4 Pick some interesting ones and re-implement them in packcc.

Thanks for the valuable information.
It's a wonderful grammar world!

**Comment by apaz-cli** [comment]
Thank you very much for your answers. And for an excellent parser generator.

I've taken some more time to familiarize myself with the project. I think that the way forward for me if I want to generate an AST is to fork the project and insert my own hooks into the generated parser. I want every rule to have its own `$$` of type `<Rule Name>Node*`, with memory allocated for it in advance. That prevents me from having to write my own allocation and cast to the correct node type every time I want to store something inside the grammar. Even if `$$` were consistently `void*` I would still have to write all the node type boilerplate anyway.

If you know a better way to do this, I'm looking forward to the AST example.
