### ISSUE TITLE
packcc-1.3.0-linux-x64.tar.gz isn't gzipped

### ISSUE THREAD

**Issue by MaxBarraclough** [arithy/packcc#7]
`packcc-1.3.0-linux-x64.tar.gz` should be named `packcc-1.3.0-linux-x64.tar` as it is a tarball, not a gzipped tarball.

It's only a minor issue, as the GNU tar command typically copes fine. (I only noticed as I explicitly passed `-z` which isn't really necessary.)

**Comment by arithy** [comment]
Sorry for my late reply.
I replaced it with the correct one.
Thanks.
