### ISSUE TITLE
EBCDIC (and UNICODE)

### ISSUE THREAD

**Issue by adesutherland** [arithy/packcc#9]
For probably irrational reasons, I have got a rough port of packcc running on a VM/370 mainframe (emulated). All good :-)

I need to change some of the code to support EBCDIC - e.g. [A-Z] is weird in EBCDIC. I am assuming that you would not be too interested in "polluting" your code with EBCDIC - however I will also try and do it in way that may support UNICODE (but perhaps this is already done). Again just interested in your thoughts.

Thanks

Adrian

**Comment by arithy** [comment]
Sorry for my late reply.
I don't plan to support EBCDIC since it is too old a specification.
Please use hexadecimal escape sequences for EBCDIC characters.

Requests are welcome.
Don't let this discourage you from sending me any requests again.
